name: Continuous Integration
on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - "**.build"
      - "**.in"
      - "**.yml"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.hpp"
      - "**.build"
      - "**.in"
      - "**.yml"

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install build dependancies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential expect
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip
      - run: python -m pip install --upgrade meson ninja

      - name: Build pfsshell
        run: |
          meson setup build/
          meson compile -C build

      - name: Install pfsshell
        run: sudo meson install

      - name: Run Test
          time tclsh pfsshelltest.tcl

      - uses: actions/upload-artifact@master
        with:
          name: pfsshell-ubuntu
          path: build/pfsshell
  build-win32:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential mingw-w64
      - run: sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
      - run: sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip
      - run: python -m pip install --upgrade meson ninja
      - run: meson setup build/ --cross-file ./external/meson_toolchains/mingw32_meson.ini
      - run: meson compile -C build archive
      - uses: actions/upload-artifact@master
        with:
          name: pfsshell-win32
          path: build/*.7z
  build-macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip
      - run: python -m pip install --upgrade meson ninja
      - run: meson setup build/
      - run: meson compile -C build
      - uses: actions/upload-artifact@master
        with:
          name: pfsshell-macos
          path: build/pfsshell

  create-release:
    needs: [build-ubuntu, build-win32, build-macos]
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
    steps:
    - name: Download ubuntu artifact
      uses: actions/download-artifact@v1
      with:
        name: pfsshell-ubuntu

    - name: Download win32 artifact
      uses: actions/download-artifact@v1
      with:
        name: pfsshell-win32

    - name: Download macos artifact
      uses: actions/download-artifact@v1
      with:
        name: pfsshell-macos

    - name: Prepare artifacts for release
      run: |
        7z a -tzip pfsshell-ubuntu.zip pfsshell-ubuntu/*
        7z a -tzip pfsshell-macos.zip pfsshell-macos/*

    - name: Create prerelease
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "Latest development builds"
        files: |
          pfsshell-ubuntu.zip
          pfsshell-win32/*
          pfsshell-macos.zip

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: "${{ contains(github.ref, '-rc') }}"
        files: |
          pfsshell-ubuntu.zip
          pfsshell-win32/*
          pfsshell-macos.zip
